version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: zap
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"